### ISSUE TITLE
Missing Numpy

### ISSUE THREAD

**Issue by TheSin-** [zebra-lucky/electrum-dash-winebuild#1]
EDIT: I just noticed my buildozer file differed upstream, the p4a dir wasn't set which contains bls, no idea why or how this happened.  I'm testing if it works I'll just close this.  Thanks and keep up the amazing work!

with the latest version, trying to build electrum-dash I keep running into a missing numpy?

```
  Added bls_py from https://files.pythonhosted.org/packages/8c/3c/c9902938cb211081d547421198a355b6713d58318dd0a31a39ca7856b77f/bls.py-0.1.2.tar.gz#sha256=73bae1ee04a757bbc40f87b98e5904bc4656dde37d5982f09aab832dceeeffca (from -r requirements.txt (line 1)) to build tracker '/tmp/pip-req-tracker-akpy72j4'
    Running setup.py (path:/tmp/pip-install-yxepombl/bls-py/setup.py) egg_info for package bls-py
    Running command python setup.py egg_info
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-yxepombl/bls-py/setup.py", line 32, in <module>
        ext_modules=get_extensions(),
      File "/tmp/pip-install-yxepombl/bls-py/setup.py", line 9, in get_extensions
        import numpy
    ModuleNotFoundError: No module named 'numpy'
```

Is this known? is there a work around?  I'm currently adding `sudo apt-get update; sudo apt-get install python3-numpy` to the DOCKER_CMD but then I run into

```
  Caching due to etag
  Added bls_py from https://files.pythonhosted.org/packages/8c/3c/c9902938cb211081d547421198a355b6713d58318dd0a31a39ca7856b77f/bls.py-0.1.2.tar.gz#sha256=73bae1ee04a757bbc40f87b98e5904bc4656dde37d5982f09aab832dceeeffca (from -r requirements.txt (line 1)) to build tracker '/tmp/pip-req-tracker-zbjkmt6j'
    Running setup.py (path:/tmp/pip-install-q2iio20l/bls-py/setup.py) egg_info for package bls-py
    Running command python setup.py egg_info
    Traceback (most recent call last):
      File "/home/buildozer/build/.buildozer/android/platform/build/build/python-installs/Electrum_TRC/numpy/core/__init__.py", line 16, in <module>
        from . import multiarray
    ImportError: cannot import name 'multiarray'
```

I haven't found a fix for this one yet and fear I'm going down the wrong path, so thought I'd ask here before I push further.  I'm not sure if it's missing in the docker image or the build receipt for electrum-dash.

**Comment by zebra-lucky** [comment]
Do you have a resolution?

Why bls-py installed?
There is python-bls==0.1.8 which is build on all platforms.

**Comment by TheSin-** [comment]
yes I do thank you for checking, the issue was in the buildozer file I had the p4a directory commented out.  I have no idea why git status wasn't showing it as changed to me.  I must have changed it when I was build 3.3.8 and forgot, no idea why I was messing around with it.  I think it was when I was helping the python-for-android guys get native OSX builds working.

Again thanks for the reply but everything is perfect, keep up the excellent work!
